# Railway configuration file for a multi-service Docker Compose project

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "8000"
SUMA_URL = "http://localhost:8001"
RESTA_URL = "http://localhost:8002"
ECUACION_URL = "http://localhost:8003"
ALMACENAR_URL = "http://localhost:8004"

# Remove individual service definitions since we're using a single container
# with multiple services managed by the start.sh script

[common.deploy.env]
PORT = "8000" 